<?php

namespace Ripple;

use mysqli;
use mysqli_result;

/**
 * Database connection for the backend.
 *
 * Extends mysqli and is used exactly like it — execute_query() returning
 * mysqli_result|bool, fetch_assoc() on the result, connect_error — with two
 * additions: insertId() and numRows(). The raw `insert_id` and `num_rows` are
 * C-level internal properties that can't be read or written on an offline
 * subclass, so callers reach them through these methods instead.
 *
 * Tests pass a subclass of this seam (tests/FakeDatabase) that overrides
 * execute_query() to return a fake mysqli_result (tests/ResultSeam) and
 * insertId()/numRows() to return canned values — no live MySQL server required.
 */
class Database extends mysqli
{
    /** ID generated by the most recent INSERT. */
    public function insertId(): int
    {
        return (int) $this->insert_id;
    }

    /** Number of rows in a result set. */
    public function numRows(mysqli_result $result): int
    {
        return (int) $result->num_rows;
    }
}
